# 要开始使用 Dependabot 版本更新，您需要指定哪些

# 请参阅文档以了解所有配置选项：
# https://docs.github.com/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file

版本：2: 2
更新：:
  - package-ecosystem: "" # 参见文档以获取可能的值package-ecosystem: "" # See documentation for possible values
    目录: "/" # 包清单的位置: "/" # Location of package manifests
    时间表::
      间隔："每周": "weekly"
