// ============================================================
// sites.js — 网站数据（整合 123.sogou.com 和 ai888.site 内容）
// 使用 var 声明全局变量，确保 main.js 能通过 window.sitesData 访问
// ============================================================
var sitesData = {
    categories: [{
        id: "common",
        name: "常用",
        icon: "fas fa-star",
        sites: [{
            id: 1,
            name: "Google",
            url: "https://www.google.com",
            icon: "https://www.google.com/favicon.ico",
            description: "全球最受欢迎的搜索引擎",
            category: "常用"
        }, {
            id: 2,
            name: "百度",
            url: "https://www.baidu.com",
            icon: "https://www.baidu.com/favicon.ico",
            description: "中国最大的搜索引擎",
            category: "常用"
        }, {
            id: 3,
            name: "必应",
            url: "https://www.bing.com",
            icon: "https://www.bing.com/favicon.ico",
            description: "微软搜索引擎",
            category: "常用"
        }, {
            id: 4,
            name: "GitHub",
            url: "https://github.com",
            icon: "https://github.githubassets.com/favicon.ico",
            description: "全球最大的代码托管平台",
            category: "常用"
        }, {
            id: 5,
            name: "Gmail",
            url: "https://mail.google.com",
            icon: "https://ssl.gstatic.com/ui/v1/icons/mail/rfr/gmail.ico",
            description: "Google 免费电子邮件服务",
            category: "常用"
        }, {
            id: 6,
            name: "YouTube",
            url: "https://www.youtube.com",
            icon: "https://www.youtube.com/favicon.ico",
            description: "全球最大的视频分享平台",
            category: "常用"
        }]
    }, {
        id: "news",
        name: "资讯",
        icon: "fas fa-newspaper",
        sites: [{
            id: 101,
            name: "新浪新闻",
            url: "https://news.sina.com.cn",
            icon: "https://www.sina.com.cn/favicon.ico",
            description: "新浪新闻门户",
            category: "资讯"
        }, {
            id: 102,
            name: "腾讯新闻",
            url: "https://news.qq.com",
            icon: "https://mat1.gtimg.com/news/favicon.ico",
            description: "腾讯新闻客户端",
            category: "资讯"
        }, {
            id: 103,
            name: "网易新闻",
            url: "https://news.163.com",
            icon: "https://static.ws.126.net/favicon.ico",
            description: "网易新闻门户",
            category: "资讯"
        }, {
            id: 104,
            name: "搜狐新闻",
            url: "https://news.sohu.com",
            icon: "https://news.sohu.com/favicon.ico",
            description: "搜狐新闻门户",
            category: "资讯"
        }, {
            id: 105,
            name: "人民日报",
            url: "https://www.people.com.cn",
            icon: "https://www.people.com.cn/img/favicon.ico",
            description: "人民日报官方网站",
            category: "资讯"
        }, {
            id: 106,
            name: "新华网",
            url: "https://www.xinhuanet.com",
            icon: "https://www.xinhuanet.com/favicon.ico",
            description: "新华通讯社官方网站",
            category: "资讯"
        }, {
            id: 107,
            name: "央视网",
            url: "https://www.cctv.com",
            icon: "https://www.cctv.com/favicon.ico",
            description: "中央电视台官方网站",
            category: "资讯"
        }]
    }, {
        id: "ai",
        name: "AI工具",
        icon: "fas fa-robot",
        sites: [{
            id: 201,
            name: "ChatGPT",
            url: "https://chat.openai.com",
            icon: "https://chat.openai.com/favicon.ico",
            description: "OpenAI 对话 AI",
            category: "AI工具"
        }, {
            id: 202,
            name: "Midjourney",
            url: "https://www.midjourney.com",
            icon: "https://www.midjourney.com/favicon.ico",
            description: "AI 绘画生成工具",
            category: "AI工具"
        }, {
            id: 203,
            name: "Stable Diffusion",
            url: "https://stability.ai",
            icon: "https://stability.ai/favicon.ico",
            description: "开源 AI 绘画模型",
            category: "AI工具"
        }, {
            id: 204,
            name: "Claude",
            url: "https://claude.ai",
            icon: "https://claude.ai/favicon.ico",
            description: "Anthropic 对话 AI",
            category: "AI工具"
        }, {
            id: 205,
            name: "文心一言",
            url: "https://yiyan.baidu.com",
            icon: "https://nlp-eb.cdn.bcebos.com/logo/favicon.ico",
            description: "百度 AI 对话助手",
            category: "AI工具"
        }, {
            id: 206,
            name: "通义千问",
            url: "https://tongyi.aliyun.com",
            icon: "https://img.alicdn.com/imgextra/i1/O1CN01o7Jc2k1s0x1F2Z7eV_!!6000000005711-2-tps-200-200.png",
            description: "阿里云 AI 大模型",
            category: "AI工具"
        }]
    }, {
        id: "study",
        name: "学习",
        icon: "fas fa-graduation-cap",
        sites: [{
            id: 301,
            name: "MDN Web Docs",
            url: "https://developer.mozilla.org",
            icon: "https://developer.mozilla.org/favicon.ico",
            description: "Web 技术权威文档",
            category: "学习"
        }, {
            id: 302,
            name: "Stack Overflow",
            url: "https://stackoverflow.com",
            icon: "https://stackoverflow.com/favicon.ico",
            description: "程序员问答社区",
            category: "学习"
        }, {
            id: 303,
            name: "Coursera",
            url: "https://www.coursera.org",
            icon: "https://www.coursera.org/favicon.ico",
            description: "世界领先的在线学习平台",
            category: "学习"
        }, {
            id: 304,
            name: "知乎",
            url: "https://www.zhihu.com",
            icon: "https://static.zhihu.com/heifetz/favicon.ico",
            description: "中文高质量问答社区",
            category: "学习"
        }, {
            id: 305,
            name: "Bilibili",
            url: "https://www.bilibili.com",
            icon: "https://www.bilibili.com/favicon.ico",
            description: "年轻世代文化社区和视频平台",
            category: "学习"
        }]
    }, {
        id: "tools",
        name: "工具",
        icon: "fas fa-tools",
        sites: [{
            id: 401,
            name: "Canva",
            url: "https://www.canva.com",
            icon: "https://www.canva.com/favicon.ico",
            description: "在线设计工具",
            category: "工具"
        }, {
            id: 402,
            name: "TinyPNG",
            url: "https://tinypng.com",
            icon: "https://tinypng.com/images/favicon.ico",
            description: "智能 PNG/JPEG 压缩",
            category: "工具"
        }, {
            id: 403,
            name: "Notion",
            url: "https://www.notion.so",
            icon: "https://www.notion.so/favicon.ico",
            description: "一体化工作空间",
            category: "工具"
        }, {
            id: 404,
            name: "CodePen",
            url: "https://codepen.io",
            icon: "https://codepen.io/favicon.ico",
            description: "前端代码在线编辑和演示",
            category: "工具"
        }, {
            id: 405,
            name: "JSON Formatter",
            url: "https://jsonformatter.org",
            icon: "https://jsonformatter.org/favicon.ico",
            description: "JSON 格式化工具",
            category: "工具"
        }]
    }, {
        id: "social",
        name: "社交",
        icon: "fas fa-users",
        sites: [{
            id: 501,
            name: "Twitter",
            url: "https://twitter.com",
            icon: "https://abs.twimg.com/favicons/twitter.ico",
            description: "社交网络和微博客服务",
            category: "社交"
        }, {
            id: 502,
            name: "Facebook",
            url: "https://www.facebook.com",
            icon: "https://www.facebook.com/favicon.ico",
            description: "全球最大社交平台",
            category: "社交"
        }, {
            id: 503,
            name: "Instagram",
            url: "https://www.instagram.com",
            icon: "https://www.instagram.com/favicon.ico",
            description: "照片和视频分享社交应用",
            category: "社交"
        }, {
            id: 504,
            name: "LinkedIn",
            url: "https://www.linkedin.com",
            icon: "https://www.linkedin.com/favicon.ico",
            description: "职场社交平台",
            category: "社交"
        }, {
            id: 505,
            name: "微信",
            url: "https://weixin.qq.com",
            icon: "https://res.wx.qq.com/a/wx_fed/assets/res/NTI4MWU5.ico",
            description: "腾讯即时通信服务",
            category: "社交"
        }]
    }, {
        id: "entertainment",
        name: "娱乐",
        icon: "fas fa-gamepad",
        sites: [{
            id: 601,
            name: "Netflix",
            url: "https://www.netflix.com",
            icon: "https://www.netflix.com/favicon.ico",
            description: "流媒体播放平台",
            category: "娱乐"
        }, {
            id: 602,
            name: "Spotify",
            url: "https://www.spotify.com",
            icon: "https://www.spotify.com/favicon.ico",
            description: "音乐流媒体服务平台",
            category: "娱乐"
        }, {
            id: 603,
            name: "Steam",
            url: "https://store.steampowered.com",
            icon: "https://store.steampowered.com/favicon.ico",
            description: "电子游戏数字发行平台",
            category: "娱乐"
        }, {
            id: 604,
            name: "豆瓣",
            url: "https://www.douban.com",
            icon: "https://www.douban.com/favicon.ico",
            description: "图书电影音乐推荐评论",
            category: "娱乐"
        }, {
            id: 605,
            name: "Twitch",
            url: "https://www.twitch.tv",
            icon: "https://www.twitch.tv/favicon.ico",
            description: "视频游戏直播平台",
            category: "娱乐"
        }]
    }, {
        id: "shopping",
        name: "购物",
        icon: "fas fa-shopping-cart",
        sites: [{
            id: 701,
            name: "淘宝",
            url: "https://www.taobao.com",
            icon: "https://www.taobao.com/favicon.ico",
            description: "阿里巴巴旗下购物平台",
            category: "购物"
        }, {
            id: 702,
            name: "京东",
            url: "https://www.jd.com",
            icon: "https://www.jd.com/favicon.ico",
            description: "综合网上购物商城",
            category: "购物"
        }, {
            id: 703,
            name: "拼多多",
            url: "https://www.pinduoduo.com",
            icon: "https://www.pinduoduo.com/favicon.ico",
            description: "社交电商平台",
            category: "购物"
        }, {
            id: 704,
            name: "亚马逊",
            url: "https://www.amazon.cn",
            icon: "https://www.amazon.cn/favicon.ico",
            description: "全球领先的电子商务平台",
            category: "购物"
        }, {
            id: 705,
            name: "美团",
            url: "https://www.meituan.com",
            icon: "https://www.meituan.com/favicon.ico",
            description: "生活服务电子商务平台",
            category: "购物"
        }]
    }, {
        id: "video",
        name: "视频",
        icon: "fas fa-video",
        sites: [{
            id: 801,
            name: "腾讯视频",
            url: "https://v.qq.com",
            icon: "https://v.qq.com/favicon.ico",
            description: "国内领先的在线视频平台",
            category: "视频"
        }, {
            id: 802,
            name: "爱奇艺",
            url: "https://www.iqiyi.com",
            icon: "https://www.iqiyi.com/favicon.ico",
            description: "高品质视频娱乐平台",
            category: "视频"
        }, {
            id: 803,
            name: "优酷",
            url: "https://www.youku.com",
            icon: "https://www.youku.com/favicon.ico",
            description: "中国领先的在线视频平台",
            category: "视频"
        }, {
            id: 804,
            name: "芒果TV",
            url: "https://www.mgtv.com",
            icon: "https://www.mgtv.com/favicon.ico",
            description: "湖南卫视官方视频平台",
            category: "视频"
        }, {
            id: 805,
            name: "抖音",
            url: "https://www.douyin.com",
            icon: "https://www.douyin.com/favicon.ico",
            description: "短视频社交平台",
            category: "视频"
        }]
    }]
};